import { Writable, Readable } from "stream";
import { Stats } from "fs";

export interface IFS {
    WriteStream: typeof Writable;
    ReadStream: typeof Readable;
    readFileSync();
    renameSync();
    ftruncateSync();
    truncateSync();
    chownSync();
    fchownSync();
    lchownSync();
    chmodSync();
    fchmodSync();
    lchmodSync();
    statSync(path:string): Stats;
    lstatSync();
    fstatSync();
    linkSync();
    symlinkSync();
    readlinkSync();
    realpathSync();
    unlinkSync();
    rmdirSync();
    mkdirSync();
    readdirSync();
    closeSync();
    openSync();
    utimesSync();
    futimesSync();
    fsyncSync();
    writeSync();
    readSync();
    readFileSync();
    writeFileSync();
    appendFileSync();
    existsSync(path): boolean;
    accessSync();
    createReadStream(path:string) : ReadableStream;
    createWriteStream(path:string) : WritableStream;
    watchFile();
    unwatchFile();
    watch();
    rename();
    ftruncate();
    truncate();
    chown();
    fchown();
    lchown();
    chmod();
    fchmod();
    lchmod();
    stat();
    lstat();
    fstat();
    link();
    symlink();
    readlink();
    realpath();
    unlink();
    rmdir();
    mkdir();
    readdir();
    close();
    open();
    utimes();
    futimes();
    fsync();
    write();
    read();
    readFile();
    writeFile();
    appendFile();
    exists();
    access();
}
